POST http://localhost:5000/retrogames-be713/us-central1/api/games HTTP/1.1
Content-Type: application/json

{
 "title": "Jogo Foda",
 "image_url": "https://t.me/virtualroms/50",
 "file_url": "https://t.me/virtualroms/60",
 "console": "Super Nintendo",
 "genre": "RPG"
}

###
http://localhost:5000/retrogames-be713/us-central1/api/games

###
//BOT API
POST http://localhost:5001/retrogames-be713/us-central1/api/bot HTTP/1.1
Content-Type: application/json

{
  "message": {
    "from": {
      "id": 318475027
    },
    "text": "/count@Bertinnnbot",
    "chat": {
      "id": 318475027
    }
  }
}